### ISSUE TITLE
참가 카풀 목록

### ISSUE THREAD

**Issue by ryush00** [ryush00/capstone#112]
본인이 참가하는 카풀 목록을 보여주는 페이지를 만들어야 함.

## 작업 내용
1. routes에 `/pools/my`로 가는 라우트를 만들고 pools controller의 my 액션으로 연결
2. my 액션에서 내가 참가중인 pool의 목록 출력

**Comment by ryush00** [comment]
내 정보에 참가 목록 넣기

**Comment by Yang0Jin0Woo** [comment]
라우트 안만들어도 될 수 있다

**Comment by ryush00** [comment]
## 작업내용
- 내 정보 오프캔버스 (오른쪽에서 튀어나오는 부분)에다가 참가 목록 보여주기

**Comment by Yang0Jin0Woo** [comment]
현재 참가한 카풀을 가지고 오는 코드를 작성하자 where문 참고
